language: node_js
sudo: false
node_js:
  - "stable"

cache:
  directories:
    - "node_modules"

env:
  - SKIP_PREFLIGHT_CHECK=true

install:
  - cd ./frontend && yarn install && cd ..

script:
  - cd frontend
  - yarn lint